# Config to create service called web from the Dockerfile
# in the project directory, and run the uvicorn command on host 0.0.0.0 port 8000
# volumes are used to mount the project directory (application code) to /usr/src/app in the container
# ports are used to expose the container port 8000 to the host port 8000
# environment variables are used to set the ENVIRONMENT and TESTING environment variables to development and 0 respectively

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
